version: '3'

services:

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .:/var/www/

  php:
    build: ./docker/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/
    links:
      - database:mysqldb
      - rabbit:rabbit
    depends_on:
      - rabbit

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    links:
      - php
      - rabbit
    volumes:
      - ./docker/nginx/logs:/var/log/nginx

  rabbit:
   image: "rabbitmq:3.7-management"
   hostname: "localhost"
   working_dir: "/var/www/"
   environment:
     - RABBITMQ_ERLANG_COOKIE=12345678
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
     - RABBITMQ_DEFAULT_VHOST=/
   volumes:
     - .:/var/www/
   ports:
     - "15672:15672"
     - "5672:5672"
